### ISSUE TITLE
Evaluation script

### ISSUE THREAD

**Issue by rave78** [justincui03/dc_benchmark#3]
It looks that [method argument](https://github.com/justincui03/dc_benchmark/blob/main/scripts/eval.sh#L3) is missing in the [run evaluation](https://github.com/justincui03/dc_benchmark#run-an-evaluation).  Also, I was wondering how to run the evaluation for _TM mode_ because the script shows an error about "images_best.pt".  How do I get that file?

**Comment by justincui03** [comment]
Hi, 

sorry for the late reply, I uploaded the condensed dataset to the shared drive:

https://drive.google.com/drive/folders/1trp0MyUoL9QrbsdQ8w7TxgoXcMJecoyH?usp=sharing

Feel free to send me an email if you have any further questions.
